name: CD

# Cancel previous runs that are not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  cd:
    name: SSH to server and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: daitran2010/crawler-website
          tags: |
            type=raw,value=latest

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: 22
          script: |
            docker rm -f website &2>/dev/null || true
            docker images --format '{{.Repository}}:{{.Tag}}' | grep 'daitran2010/crawler-website' | xargs -r docker rmi -f
            docker run --net crawler -d --name website -p 3100:80 ${{ steps.meta.outputs.tags }}
        continue-on-error: true